force-app/main/default/objects/Account/fields/Data_Origination__c.field-meta.xml
<CustomField>
    <fullName>Data_Origination__c</fullName>
    <label>Data Origination (DO NOT USE)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Origination__c/Data_Origination__c.object-meta.xml
<CustomObject>
    <label>Data Origination</label>
    <nameField>
        <label>Data Origination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Originations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CSVRecordUploaderControllerTest.cls
@IsTest 
public class CSVRecordUploaderControllerTest {

    @IsTest
    static void testGetNumberOfRows(){
        
        Test.startTest();
        String csvStrContent = 'First Name\nTest';
        Decimal count = CSVRecordUploaderController.getNumberOfRows(csvStrContent);
        System.assertEquals(2, count);
        Test.stopTest();
        
        Data_Origination__c dataOri = new Data_Origination__c();
        dataOri.Name = 'test';
        Insert dataOri;
         
    }
    
    @IsTest
    static void testCreateRecordAccount(){
        
        Test.startTest();
        String csvStrContent = 'Company Name\n"Test, test-test"';
        CSVRecordUploaderController.createRecord(csvStrContent, 'Account');
        Test.stopTest();
        
    }
    
    @IsTest
    static void testCreateRecordContact(){
        
        Test.startTest();
        Account newAcc = new Account();
        newAcc.Name = 'test';
        newAcc.Beauhurst_ID__c = '3245';
        insert newAcc;
        String csvStrContent = 'FirstName,LastName,Registered Number\nTest,Test,3245';
        CSVRecordUploaderController.createRecord(csvStrContent, 'Contact');
        Test.stopTest();
    }
    

}